name: tachidesk_sorayomi
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.8.1
  flutter_mobx: ^2.0.6+1
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^4.2.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  mobx: ^2.0.7+5
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  share_plus: ^4.0.10
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_flavorizr: ^2.1.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  go_router_builder: ^1.0.7
  hive_generator: ^1.1.3
  json_serializable: ^6.3.1
  lints: ^2.0.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

flavorizr:
  ide: "vscode"
  app:
    android:
      flavorDimensions: "flavor-type"
    ios: null

  flavors:
    release:
      app:
        name: "Sorayomi"
        icon: assets/icons/launcher/sorayomi_icon.png

      android:
        applicationId: "com.suwayomi.tachidesk_sorayomi"

      ios:
        bundleId: "com.suwayomi.tachidesk_sorayomi"
        name: "Sorayomi"

    preview:
      app:
        name: "Sorayomi Preview"
        icon: assets/icons/launcher/sorayomi_preview_icon.png

      android:
        applicationId: "com.suwayomi.tachidesk_sorayomi.preview"
      ios:
        bundleId: "com.suwayomi.tachidesk_sorayomi.preview"
        name: "Sorayomi Preview"